# Generated by Django 4.1.7 on 2023-03-13 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('state_or_private', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('operation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=30)),
                ('operation', models.CharField(max_length=30)),
                ('number_type', models.CharField(max_length=30)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.translationparticipants')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_series', models.IntegerField()),
                ('passport_number', models.IntegerField()),
                ('division_code', models.IntegerField()),
                ('place_of_residence', models.CharField(max_length=30)),
                ('participant_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.translationparticipants')),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.IntegerField()),
                ('currency', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, verbose_name=[])),
                ('time', models.TimeField(blank=True, verbose_name=[])),
                ('operation', models.CharField(max_length=30)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.translationparticipants')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bank')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.translationparticipants')),
            ],
        ),
    ]
